cc_library(
    name = "common",
    srcs = [],
    hdrs = [
        "day.hpp",
        "input.hpp",
    ],
    compiler_flags = [
        "-O2",
        "-std=c++20",
    ],
    visibility = [
        "//aoc/src/...",
    ],
    deps = [
        "///third_party/cc/fmt",
    ],
)
