plugin_repo(
  name = "cc",
  revision = "v0.4.0",
  plugin = "cc-rules",
  owner = "please-build",
)

# My personal repo for trying to fix small things in please
# plugin_repo(
#   name = "cc",
#   revision = "spaces-fix",
#   plugin = "cc-rules",
#   owner = "rHermes",
# )
